# Generated by Django 5.2.10 on 2026-01-09 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='pools.season'),
            preserve_default=False,
        ),
    ]
