# Generated by Django 5.2.10 on 2026-01-09 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_contestant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entry',
            name='first_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_out_entries', to='pools.contestant'),
        ),
        migrations.AddField(
            model_name='entry',
            name='winner_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner1_entries', to='pools.contestant'),
        ),
        migrations.AddField(
            model_name='entry',
            name='winner_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner2_entries', to='pools.contestant'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('pool', 'user'), name='uniq_user_per_pool'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('first_out__isnull', False)), fields=('pool', 'first_out'), name='uniq_first_out_per_pool'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('winner_1__isnull', True), ('winner_2__isnull', True), models.Q(('winner_1', models.F('winner_2')), _negated=True), _connector='OR'), name='chk_winners_distinct'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('first_out__isnull', True), ('winner_1__isnull', True), models.Q(('first_out', models.F('winner_1')), _negated=True), _connector='OR'), name='chk_firstout_not_winner1'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('first_out__isnull', True), ('winner_2__isnull', True), models.Q(('first_out', models.F('winner_2')), _negated=True), _connector='OR'), name='chk_firstout_not_winner2'),
        ),
    ]
