# Generated by Django 5.2.10 on 2026-01-09 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0006_alter_entry_unique_together_entry_first_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('eliminated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminated_in_episodes', to='pools.contestant')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='pools.season')),
            ],
            options={
                'ordering': ['season', 'number'],
                'unique_together': {('season', 'number')},
            },
        ),
    ]
