# Generated by Django 5.2.10 on 2026-01-14 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0007_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='sole_survivor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_seasons', to='pools.contestant'),
        ),
    ]
