# Generated by Django 5.2.10 on 2026-02-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0008_season_sole_survivor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cast/season-50/'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='tribe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
