# Generated by Django 5.2.10 on 2026-02-18 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0009_contestant_bio_contestant_eliminated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='first_out_pick_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='first_out_picked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='first_out_draft_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='first_out_draft_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='previous_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_pool_winner_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('first_out_pick_order__isnull', False)), fields=('pool', 'first_out_pick_order'), name='uniq_first_out_order_per_pool'),
        ),
    ]
