# Generated by Django 5.2.10 on 2026-04-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0010_entry_first_out_pick_order_entry_first_out_picked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='eliminated',
        ),
        migrations.AddField(
            model_name='episode',
            name='eliminated',
            field=models.ManyToManyField(blank=True, related_name='eliminated_in_episodes', to='pools.contestant'),
        ),
    ]
